# netlify.toml

[build]
  command = "npm run build"  # Adjust this based on your client build command
  publish = "client/build"   # Adjust this based on your client build output

[[redirects]]
  from = "/api/*"
  to = "http://localhost:9999/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Set environment variables needed for your server build
    GOOGLE_APPLICATION_CREDENTIALS="deno-chatbot-grfc-e9ed84a6ca53.json"
    MONGODB_URI="mongodb+srv://deeppjp1656:1234567890@advancedchat.gbjhu9o.mongodb.net/?retryWrites=true&w=majority"
    NODE_ENV="production"