[build]
  command = "npm run build"  # Replace with your build script
  publish = "dist"  # Replace with the path to your build output

[[functions]]
  directory = "functions"  # Replace with the path to your serverless functions
  include = ["*.js", "*.ts"]  # Adjust file extensions accordingly
